export const REQUEST_ACTION = 'auth/REQUEST_ACTION';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';
export const GET_DETAILS_SUCCESS = 'auth/GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAILURE = 'auth/GET_DETAILS_FAILURE';

